### ISSUE TITLE
Pkg versioning formatting

### ISSUE THREAD

**Issue by MiqViq** [maxschlapfer/MacAdminHelpers#3]
Hi,

I would prefer that pkg name formatting would be like Keynote-6.6.1.pkg.
Otherwise tools like munkiimport (item importing tool for Munki) will rename the installer pkg as Keynote_6.6.1-6.6.1.pkg.
Not a big issue really but saves a couple of bytes from the filename...

**Comment by maxschlapfer** [comment]
Hi MiqViq

Thanks for this input, I wasn't aware of this, as we do not use munki ourself. I added an option "-m" to make the output munkiimport friendly. Just start the script with "AppStoreExctract.sh -m" and the output will be "Keynote-6.6.1.pkg" (resp. Keynote-6.6.1.dmg).

Hope this helps make it smoother for all munki users.

**Comment by MiqViq** [comment]
Thanks for your creative input!

Still not understand how many people rename Munki as "munch" in their heads...
It is Munki (or Managed Software Center to users).
Calling it "munch" always brings the painting "The Scream" by Edvard Munch in my mind's eye...

br,

MiqViq

**Comment by erikng** [comment]
Blame iOS' autocorrect.

**Comment by maxschlapfer** [comment]
The "Munch" was - as erikng mentioned - based on autocorrect under OS X (this time it was not iOS to blame).
