### ISSUE TITLE
office.fonts is required

### ISSUE THREAD

**Issue by clburlison** [maxschlapfer/MacAdminHelpers#4]
> The following Installer Choices are available (with version 15.18): `word` `excel` `powerpoint` `onenote.mac` `outlook` `autoupdate` and `office.fonts`

Too lazy to make a PR atm. However the source from the Slack #microsoft-office channel is linked below. `office.fonts` is not optional. If you exclude it in a install it will result in the applications not working. 

https://macadmins.slack.com/archives/microsoft-office/p1447219794000886 & https://macadmins.slack.com/archives/microsoft-office/p1447220771000932

**Comment by maxschlapfer** [comment]
Thanks for this information, I did remove the option and made a note in the README, when I have time I will implement a short check routine to prevent accidentally removal of these parts.

**Comment by maxschlapfer** [comment]
I have included some parameter checking to prevent entering wrong or unsupported InstallChoices. Only the "official" InstallChoices are now accepted: word, excel, powerpoint, onenote.mac, outlook ,and autoupdate.

**Comment by clburlison** [comment]
I only visually checked but LGTM.

Solved: https://github.com/maxschlapfer/MacAdminHelpers/compare/e96894189ed0adef204d2ed8cc6f074cf576c202...a1e5069cc84532be58ba75c047ad269244f034ea
