### ISSUE TITLE
Full Suite Installer Name Changed

### ISSUE THREAD

**Issue by csteelatgburg** [maxschlapfer/MacAdminHelpers#6]
It appears that the filenames for the full suite installers have changed:
http://macadmins.software/15.19.1/Microsoft_Office_2016_Installer.pkg
http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.22.0_160506_Installer.pkg

15.19.1 was the last version that worked for me using the script. When the package runs now it is still looking for Microsoft_Office_2016_Installer.pkg which no longer exists.

**Comment by csteelatgburg** [comment]
Updating line 143 to instruct curl to save the file as Microsoft_Office_2016_Installer.pkg resolved the issue:
(cd ${SCRIPT_DIR}; curl -o Microsoft_Office_2016_Installer.pkg -LsOJ $FULL_INSTALLER)

**Comment by maxschlapfer** [comment]
Hi csteelatgburg

Thanks for this info, this name change should not impact the script, as it already renames the downloaded file to the standardised package name "Microsoft_Office_2016_Installer.pkg" but this change was already implemented on April 13th. Maybe you were using an older version of the script?

**Comment by csteelatgburg** [comment]
Ah, I missed that update. Thanks!

**Comment by maxschlapfer** [comment]
no problem.
