### ISSUE TITLE
VL serializer pkg name changed

### ISSUE THREAD

**Issue by dhmoore** [maxschlapfer/MacAdminHelpers#7]
On a freshly downloaded full install ISO from the volume licensing service center, the serializer is named "Microsoft_Office_2016_VL_Serializer_2.0.pkg". The script expects "Microsoft_Office_2016_VL_Serializer.pkg".

**Comment by maxschlapfer** [comment]
Dear dhmoore, thanks for the information, I will try to issue an update to reflect this change as soon as possible.

**Comment by maxschlapfer** [comment]
Dear dhmoore, I just updated the script. It should now work as expected with version 2.0 of the serializer. Thanks again for the update.
