### ISSUE TITLE
AppStoreExtract.sh

### ISSUE THREAD

**Issue by daroloson** [maxschlapfer/MacAdminHelpers#9]
**Press any key to finish after downloading new software from AppStore.**

seems to ignore space, tab, return, and enter.

**Comment by maxschlapfer** [comment]
Hi daroloson,

Thanks for this catch. I was able to make the Return/Enter key(s) work, but not the Spacebar or Tab, yet. Have to investigate and test further here before changing the script.

**Comment by daroloson** [comment]
Well at least I wasn't delusional, I thought most people for "any key" would hit space or return
so why wouldn't this have been reported day one.

**Comment by daroloson** [comment]
http://stackoverflow.com/questions/5297638/bash-how-to-end-infinite-loop-with-any-key-pressed

You need to put the standard input in non-blocking mode. Here is an example that works:

    #!/bin/bash

     if [ -t 0 ]; then stty -echo -icanon -icrnl time 0 min 0; fi

     count=0
     keypress=''
      while [ "x$keypress" = "x" ]; do
       let count+=1
       echo -ne $count'\r'
       keypress="`cat -v`"
      done

      if [ -t 0 ]; then stty sane; fi

      echo "You pressed '$keypress' after $count loop iterations"
      echo "Thanks for using this script."
      exit 0

Edit 2014/12/09: Add the -icrnl flag to stty to properly catch the Return key, use cat -v instead of read in order to catch Space.

It is possible that cat reads more than one character if it is fed data fast enough; if not the desired behaviour, replace `cat -v` with `dd bs=1 count=1 status=none | cat -v`.

**Comment by maxschlapfer** [comment]
Hi daroloson

As far as I can tell, the problem is solved, thanks for the input.

Tested under Sierra 10.12.3, everything seems to work. If you have time, please test in your environment.
